# Generated by Django 4.2.3 on 2023-07-24 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson', to='lms.course', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.ImageField(null=True, upload_to='course/', verbose_name='превью'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.ImageField(null=True, upload_to='course/', verbose_name='превью'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.URLField(null=True, verbose_name='ссылка на видео'),
        ),
    ]
