# Generated by Django 4.2.3 on 2023-07-25 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0002_lesson_course_alter_course_preview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_at', models.DateField(auto_now_add=True, verbose_name='дата оплаты')),
                ('payment_amount', models.PositiveIntegerField(verbose_name='сумма оплаты')),
                ('payment_method', models.CharField(choices=[('CA', 'Cash'), ('TR', 'Transfer')], default='CA', max_length=2, verbose_name='способ оплаты')),
                ('paid_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.course', verbose_name='оплаченный курс')),
                ('paid_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.lesson', verbose_name='оплаченный урок')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-paid_at',),
            },
        ),
    ]
