# Generated by Django 4.2.3 on 2023-07-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_alter_lesson_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на видео'),
        ),
    ]
