# Generated by Django 4.2.3 on 2023-08-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=0, max_length=30, verbose_name='Идентификатор платежа у Stripe'),
            preserve_default=False,
        ),
    ]
