# Generated by Django 4.2.3 on 2023-08-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='статус платежа'),
        ),
    ]
