# Generated by Django 4.2.3 on 2023-08-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время последнего обновления'),
        ),
    ]
