# Generated by Django 4.2.3 on 2023-08-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_subscription_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='last_update',
        ),
        migrations.AddField(
            model_name='course',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время последнего обновления'),
        ),
    ]
